# Generated by Django 4.1 on 2024-09-15 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_hospital"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="available_beds",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="total_beds",
        ),
        migrations.AddField(
            model_name="hospital",
            name="address",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hospital",
            name="beds_available",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hospital",
            name="beds_total",
            field=models.IntegerField(default=0),
        ),
    ]
